name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  get-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Info
        run: echo "This job was automatically triggered by a ${{github.event_name}} event on ${{github.repository}}!!!"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

